name: Generate Pacman Graph
on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate SVG
        uses: liununu/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output_name: "pacman"
          output_branch: "output"

      - name: Commit and Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          directory: dist
